require("settings")
require("mappings")
require("packer-config")
require("plenary-config")
require("color-scheme-config.tokyonight")
require("nvim-tree-config")
require("tree-sitter-config")
require("cmp-config")
require("mason-lsp-config")
require("lsp-config")
require("null-ls-config")
require("airline-config")
require("git-sign-config")
-- require("presence-config")
require("diagnostic-config")
require("vim-cmd")
